src/header/AuthenticatedUserDropdown.jsx
src/header/HeaderLearning.jsx
src/tab-page/TabContainer.jsx
src/tab-page/TabPage.jsx

Filter features after editing in the admin.

feature/toggle_feature - toggle feature course and user

---

src/course-home/outline-tab/CollapsibleSequenceLink.scss
src/course-home/outline-tab/CollapsibleSequenceLinkUnit.jsx
src/course-home/outline-tab/CollapsibleSequenceLinkUnit.scss
src/course-home/outline-tab/SectionListUnit.jsx
src/course-home/outline-tab/SectionUnit.jsx
src/course-home/outline-tab/SectionUnit.scss
src/course-tabs/CourseTabsNavigation.jsx
src/courseware/course/Course.jsx
src/courseware/course/course.scss
src/courseware/course/sequence/Sequence.jsx
src/courseware/course/sequence/Unit.jsx
src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
src/courseware/course/sequence/sequence-navigation/SequenceNavigationTabs.jsx
src/courseware/course/sidebar/common/SidebarBase.jsx
src/footer/Footer.scss
src/header/HeaderLearning.jsx
src/index.scss
src/learner-dashboard/Dashboard.jsx
src/tab-page/TabPage.jsx

- Unit Content 
- Menu Lesson 
- Menu Course 
- [GEN-402](https://www.notion.so/S-a-l-i-giao-di-n-Unit-Content-e31e77f17c8f484982cf7575678f08cd?pvs=4)
- [GEN-316](https://www.notion.so/T-o-ph-n-menu-Danh-m-c-kh-a-h-c-291679f2750a41349a13ea20505b9735?pvs=4)
- [GEN-317](https://www.notion.so/T-o-ph-n-menu-b-i-h-c-c287e38fc4a9471eb29c8f9cfa91c491?pvs=4)

feat: unit_content menu_lesson menu_course

---

src/courseware/course/sequence/Sequence.jsx

Listen to message from learning project xblock to make ui responsive: resize height and scroll in to view.

Feature (learning project xblock): listen to message from learning project xblock to make ui responsive

---

src/course-tabs/CourseTabsNavigation.jsx
src/index.scss

- Fix icon name link
- [GEN-401](https://www.notion.so/T-o-ph-n-menu-ChatGPT-ad7ae8ee74664fdaa92adbf75db3845d?pvs=4)
- [GEN-473](https://www.notion.so/S-a-l-i-c-c-l-i-giao-di-n-c5f09ba4e7d24b7b8742a28ac3bd55e2?pvs=4)
- [GEN-475](https://www.notion.so/S-a-l-i-c-c-link-Footer-13f65f4b6f6d4c22922b4c11f6d0b4ca?pvs=4)
- [GEN-474](https://www.notion.so/T-m-hi-u-v-c-c-css-variable-trong-MFE-ce662823c27749e5af215d227f9bacfb?pvs=4)
Fix icon name link

fix: fix name icon

---

src/courseware/course/sequence/Sequence.jsx
src/courseware/course/sequence/SequenceContent.jsx

Support scroll, resize height, reload iframes which contain learning project xblock.

feature: learningprojectxblock responsive

---

src/courseware/course/sequence/sequence-navigation/SequenceNavigationTabs.jsx

Fix height responsive when navigate between two leanring project xblock units.

fix (learning project xblock): ui responsive

---

src/course-home/outline-tab/CollapsibleSequenceLinkUnit.jsx
src/courseware/course/Course.jsx
src/learner-dashboard/CourseBtn.jsx

Fix  text-decoration,  turn off pgn__checkpoint

fix: fix text decoration adn pgn__checkpoint

---

src/course-home/outline-tab/CollapsibleSequenceLinkUnit.jsx
src/course-home/outline-tab/CollapsibleSequenceLinkUnit.scss
src/course-tabs/CourseTabsNavigation.jsx
src/courseware/course/Course.jsx
src/courseware/course/course.scss
src/courseware/course/sequence/Unit.jsx
src/courseware/course/sequence/sequence-navigation/SequenceNavigationTabs.jsx
src/header/HeaderLearning.jsx
src/index.scss
src/instructor-toolbar/InstructorToolbar.jsx
src/learner-dashboard/Dashboard.jsx
src/learner-dashboard/dashboard.scss
src/product-tours/data/slice.js

Fix some bug hover title,  no course fontsize, background gap, popup, scroll unlimited

fix: fix some bug hover-title-dashboard, bug scroll, bug popup

---

src/course-home/outline-tab/CollapsibleSequenceLinkUnit.jsx
src/course-home/outline-tab/CollapsibleSequenceLinkUnit.scss
src/courseware/course/bookmark/BookmarkButton.jsx
src/courseware/course/sequence/SequenceContent.jsx
src/index.scss

fix: fix bookmark and title

---

src/courseware/course/sequence/sequence-navigation/AIChatbot/AIChatbotAPI.js

fix (chatbot): api base url

---

src/courseware/course/sequence/Sequence.jsx
src/courseware/course/sequence/sequence-navigation/AIChatbot/AIChatbot.jsx

Fix: scroll into view after submit project

Fix: scroll into view after submit project

---

src/course-home/outline-tab/CollapsibleSequenceLink.jsx

Fix course outline ui:  remove (<number> question) from subsection title, remove time to complete.

fix course outline ui

---

src/course-home/outline-tab/CollapsibleSequenceLink.jsx
src/course-home/outline-tab/CollapsibleSequenceLink.scss

Fix (course outline ui): is leanring and completed css

Fix (course outline ui): is leanring and completed css

---

src/course-home/outline-tab/CollapsibleSequenceLink.jsx

fix (course outline ui): is learning and completed unit

fix (course outline ui): is learning and completed unit

---

src/courseware/course/sequence/sequence-navigation/AIChatbot/AIChatbot.scss

Add more padding for chatbot messages container if is firefox.

fix (chatbot ui): messages list padding for firefox

---

src/courseware/course/sequence/sequence-navigation/AIChatbot/AIChatbot.scss

fix (chatbot ui): background color

fix (chatbot ui): background color

---

src/courseware/course/sequence/Sequence.jsx
src/courseware/course/sequence/SequenceContent.jsx
src/courseware/course/sequence/sequence-navigation/AIChatbot/AIChatbot.scss
src/courseware/course/sequence/sequence-navigation/Feedback/Feedback.jsx

Fix: 
- remove chatbot border left and right. 
- set timeout when scroll by learningprojectxblock event.

fix: remove chatbot borders, settimeout for learningproject scroll event

---

src/course-home/outline-tab/CollapsibleSequenceLink.jsx
src/course-home/outline-tab/CollapsibleSequenceLink.scss
src/courseware/course/sequence/sequence-navigation/AIChatbot/AIChatbot.jsx

Fix/courseoutline UI

---

src/courseware/course/sequence/Sequence.jsx
src/courseware/course/sequence/sequence-navigation/AIChatbot/AIChabotAssets.jsx

Add unit.resize event listener.

Feature: resize unit event

---

src/course-home/outline-tab/CollapsibleSequenceLinkUnit.jsx
src/course-home/outline-tab/CollapsibleSequenceLinkUnit.scss

fix: increase leftbar clickable area

fix: increase leftbar clickable area

---

src/course-home/outline-tab/CollapsibleSequenceLinkUnit.jsx
src/course-home/outline-tab/CollapsibleSequenceLinkUnit.scss

fix: left bar clickable area

---

src/course-home/outline-tab/SectionListUnit.jsx
src/courseware/course/Course.jsx
src/courseware/course/bookmark/data/api.js
src/courseware/course/sequence/Sequence.jsx
src/courseware/course/sequence/sequence-navigation/Feedback/Feedback.jsx
src/courseware/course/sequence/sequence-navigation/UnitNavigation.jsx
src/index.jsx
src/index.scss
webpack.prod.config.js

Complete button, result btn, webpack config

Feature/complete button, result btn, webpack config

---

src/course-home/data/thunks.js
src/course-home/dates-tab/FunixDatesTab.jsx
src/course-tabs/CourseTabsNavigation.jsx
src/course-tabs/SkeletonTabs.jsx
src/courseware/CoursewareContainer.jsx
src/courseware/course/AIChatbot/AIChatbot.jsx
src/courseware/course/sequence/Sequence.jsx
src/courseware/course/sequence/SequenceContent.jsx
src/courseware/course/sequence/SkeletonContent.scss
src/courseware/course/sequence/SkeletonSequence.jsx
src/header/HeaderLearning.jsx
src/index.scss
src/tab-page/LoadedTabPage.jsx
src/tab-page/LoadedTabPage.jsx.old
src/tab-page/SkeletonCourseware.jsx
src/tab-page/SkeletonDates.jsx
src/tab-page/SkeletonOutline.jsx
src/tab-page/TabContainer.jsx
src/tab-page/TabPage.jsx
src/tab-page/TabPage.jsx.old
src/tab-page/data/slice.js

Feature: not re-render header and course tabs navigation

Feature: not re-render header and course tabs navigation

---

src/course-tabs/CourseTabsNavigation.jsx

fix: tabs url to path

---

src/course-home/outline-tab/CollapsibleSequenceLink.scss

fix: course outline angle btn css

fix: course outline angle btn css

---

src/courseware/course/sequence/Sequence.jsx

- Change data postmessgas submit quiz

feat : change data postmessage submit quiz

---

src/course-tabs/CourseTabsNavigation.jsx
src/header/HeaderLearning.jsx
src/learner-dashboard/CourseBtn.jsx
src/learner-dashboard/CourseList.jsx
src/utils.js

chore: change a to Link, set header height fixed.

chore: change a to Link

---

src/courseware/course/sequence/SequenceContent.jsx

fix (unit loading): remove unit iframe loading by remove skeleton.

fix (unit loading): remove unit iframe loading

---

src/course-tabs/CourseTabsNavigation.jsx

fix: fix course tab link

---

src/courseware/course/Course.jsx

Fix call api  gets status project

fix: fix call api status project

---

src/learner-dashboard/CourseBtn.jsx
src/learner-dashboard/CourseDashboardItem.jsx
src/learner-dashboard/CourseDashboardItem.scss
src/learner-dashboard/CourseList.jsx
src/learner-dashboard/CustomLink.jsx
src/learner-dashboard/Dashboard.jsx
src/learner-dashboard/api.js

Make click on dashboard course resume buttonnot reload all page.  
Temp responsive for dashboard.

feature (dasboard): course resume btn. temp responsive

---

public/index.html
src/footer/Footer.scss
src/header/HeaderLearning.scss
src/index.scss

fix: fix header-title

---

src/course-tabs/CourseTabsNavigation.jsx

Complete hide dates and discussion on course nav

feat: hide dates and discussion on course nav

---

src/courseware/course/AIChatbot/AIChatbot.jsx
src/courseware/course/AIChatbot/AIChatbot.scss
src/courseware/course/AIChatbot/QueryList.jsx

- set font-size and font-family for chatbot. 
- scroll down when pick session. 
- fix error when pick session item that has session id is equivalent to the current session id. 
-

Fix/chatbot UI ux

---

src/courseware/course/course.scss

change Unit title font size and family

fix: unit title font-size and family

---

src/courseware/course/course.scss

fix: chan unit title font size to 33px

fix: chan unit title font size to 33px

---

public/index.html
src/course-tabs/CourseTabsNavigation.jsx

remove bootstrap icons and font-awesome.

imp: remove bootstrap icons and font-awesome. 

---

src/course-home/outline-tab/CollapsibleSequenceLink.jsx
src/course-home/outline-tab/CollapsibleSequenceLinkUnit.jsx
src/courseware/course/sequence/SequenceContent.jsx

fix: comment out unused api

---

src/courseware/course/course.scss
src/courseware/course/sequence/SequenceContent.jsx
src/index.scss

fix: error when next or prev unit. rightbar ui

fix: error when next or prev unit. rightbar ui

---

src/courseware/course/AIChatbot/AIChabotAssets.jsx
src/courseware/course/AIChatbot/AIChatbot.jsx
src/courseware/course/AIChatbot/AIChatbot.scss
src/courseware/course/AIChatbot/AIChatbotAPI.js
src/courseware/course/AIChatbot/AIChatbotFooter.jsx
src/courseware/course/AIChatbot/AIChatbotHeader.jsx
src/courseware/course/AIChatbot/ChatbotFeedbackModal.jsx
src/courseware/course/AIChatbot/ChatbotFeedbackModal.scss
src/courseware/course/AIChatbot/QueryItem.jsx
src/courseware/course/AIChatbot/QueryList.jsx
src/courseware/course/AIChatbot/SessionItem.jsx
src/courseware/course/AIChatbot/SessionList.jsx
src/courseware/course/AIChatbot/slice.js
src/courseware/course/Course.jsx
src/courseware/course/course.scss
src/store.js

feature: chatbot thumbdown and feedback

feature: chatbot thumbdown feedback

---

src/courseware/course/sequence/SequenceContent.jsx

feature: unit skeleton

---

src/connection/chatbot.js
src/courseware/course/AIChatbot/AIChatbot.jsx
src/courseware/course/AIChatbot/AIChatbotAPI.js
src/courseware/course/AIChatbot/AIChatbotFooter.jsx
src/courseware/course/AIChatbot/AIChatbotHeader.jsx
src/courseware/course/AIChatbot/AIChatbotHeader.scss
src/courseware/course/AIChatbot/ChatbotListError.jsx
src/courseware/course/AIChatbot/ChatbotListError.scss
src/courseware/course/AIChatbot/ConnectionError.jsx
src/courseware/course/AIChatbot/QueryItem.jsx
src/courseware/course/AIChatbot/QueryList.jsx
src/courseware/course/AIChatbot/SessionItem.jsx
src/courseware/course/AIChatbot/SessionList.jsx
src/courseware/course/AIChatbot/messages.js
src/courseware/course/AIChatbot/slice.js
src/i18n/messages/vi.json

Feature: chatbot streaming

---

src/connection/chatbot.js
src/course-home/outline-tab/widgets/CourseTools.jsx
src/courseware/course/AIChatbot/AIChatbot.jsx
src/courseware/course/AIChatbot/AIChatbotFooter.jsx
src/courseware/course/AIChatbot/AIChatbotHeader.scss
src/courseware/course/AIChatbot/QueryItem.jsx
src/courseware/course/AIChatbot/QueryList.jsx
src/courseware/course/AIChatbot/slice.js

fix: remove some text. retry connect handle

fix: remove some text. retry connect handle

---

src/courseware/course/AIChatbot/AIChatbot.jsx
src/courseware/course/sequence/SequenceContent.jsx

Fix/unit bottom gap and chatbot courseID

Fix/unit bottom gap and chatbot courseID

---

src/course-about/courseAbout.scss

chore: css about-card

---

src/course-about/CourseAbout.jsx

- Fix color display name course

chore : css color display name course

---

src/learner-dashboard/CourseDashboardItem.jsx

Begin button at course dashboard navigate to the first unit of the course.

feature: course begin button url for dashboard

---

src/courseware/course/AIChatbot/ChatbotFeedbackModal.jsx
src/courseware/course/AIChatbot/QueryItem.jsx
src/courseware/course/AIChatbot/messages.js
src/i18n/messages/vi.json

fix: chatbot thumbdown feedback translation

fix: chatbot thumbdown feedback translation

---

src/course-about/component/ExpertTeacher.jsx
src/course-about/component/StartTeacher.jsx

- Change name title teacher template

chore : change name template teacher

---

src/course-tabs/CourseTabsNavigation.jsx
src/courseware/course/AIChatbot/AIChatbot.jsx
src/courseware/course/Course.jsx
src/courseware/course/sequence/Sequence.jsx
src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
src/courseware/course/sequence/sequence-navigation/SequenceNavigationTabs.jsx
src/header/AuthenticatedUserDropdown.jsx
src/instructor-toolbar/InstructorToolbar.jsx
src/tab-page/LoadedTabPage.jsx

fix: header no defined
